### ISSUE TITLE
Improve the tutorial and issue sending a POST request from Botsing server

### ISSUE THREAD

**Issue by mboussaa** [STAMP-project/botsing-github-app#5]
Hi,
I was trying to follow the steps described in the readme file but I could not understand much how to proceed. I explain how I proceeded:
-In application.properties: I set the `githubOAuth2Token` and `server.port`
-mvn clean package
-java -jar target/botsing-server-1.0.0.jar
-I escaped the `Run it under corporate proxy` part
-In New GitHub App, what are the `homepage url` and `webhook URL`

Could you please provide examples of application.properties and GitHub App field values that I can follow? 

Thanks.
Mohamed Boussaa (AEeon)

**Comment by luandrea** [comment]
Hi Mohamed,
the homepage url should be an URL to a page where you can put a description of the plugin, for botsing we don't need one, so you can put the URL where the botsing-server will be available.
The really important parameter is the webhook URL that is the URL that will be called from Github when something happens in the repository. This would be the URL of the services exposed by botsing-server itself.

It should be something like:
http://BOTSING_SERVER_IP:PORT/botsing-server

**Comment by mboussaa** [comment]
Thanks @luandrea.
I used http://127.0.0.1:8086/botsing-server as URL is it right? (8086 is the port I defined in application.properties)
Next, where should I add the Botsing properties file?

**Comment by luandrea** [comment]
Hi @mboussaa,
that URL is not valid because GitHub cannot reach it. It should be a public URL.
The application.properties file can be at the same level at the botsing-server-1.0.0.jar.
The Botsing properties are stored in the .botsing file inside the repository itself.

This is an example of a .botsing file:
```
group_id=org.ow2.authzforce
artifact_id=authzforce-ce-core-pdp-testutils
version=13.3.1
search_budget=60
global_timeout=90
population=100
package_filter=org.ow2.authzforce
```

**Comment by mboussaa** [comment]
Hello @luandrea  

So, I updated the config according to your helpful comments:
-Botsing server is running under http://d9b01381.ngrok.io (using ngrok to forward http://localhost:8086)
-The webhook URL is now updated: http://d9b01381.ngrok.io/botsing-server
-githubOAuth2Token and server.port (8086) are set in application.properties
-mvn clean package and java -jar target/botsing-server-1.0.0.jar to run the server
-.botsing is added to test repo https://github.com/mboussaa/Botsing-server-test 
-an issue is created in https://github.com/mboussaa/Botsing-server-test/issues/1

Nothing happens when creating the issue. Am I missing something? 
Thanks.

cc @MaelAudren

**Comment by luandrea** [comment]
Did you enabled the GitHub Botsign application that you created to access to your repository?

**Comment by mboussaa** [comment]
Yes, as you mentioned in the guide, I enabled:
read and write the repository
read and write the issues
read and write the pull requests.

**Comment by mboussaa** [comment]
Yes, as you mentioned in the guide, I enabled:
read and write the repository
read and write the issues
read and write the pull requests.

<img width="957" alt="Screenshot 2019-11-07 at 12 15 32" src="https://user-images.githubusercontent.com/5878565/68384672-687d1880-0158-11ea-8cd4-d390a92d0204.png">

**Comment by luandrea** [comment]
Ok, you should add the access to the code, because it have to read the .botsing file.

Im my settings I have:
![image](https://user-images.githubusercontent.com/1321508/68385453-1210d980-015a-11ea-8840-56bd0e9b8506.png)

And you can also take a look at the log that the botsing-server should write and see if there are errors.

**Comment by mboussaa** [comment]
![Screenshot 2019-11-07 at 14 53 41](https://user-images.githubusercontent.com/5878565/68395971-067cdd00-0171-11ea-896e-492d82b0526c.png)
<img width="1440" alt="Screenshot 2019-11-07 at 15 12 56" src="https://user-images.githubusercontent.com/5878565/68396018-1ac0da00-0171-11ea-9d2f-c14a463900cc.png">
according to logs, nothing has been done by the server. I guess the connection to the server through the git app has an issue

**Comment by luandrea** [comment]
Hi @mboussaa ,
can you check other settings in Profile > Developer Settings > GitHub Apps > Botsing-server-test Edit?
General: the Webhook URL should be public and give access to botsing-server services.
Repository Permissions: Contents=RW, Issues=RW, Metadata=RO
Events: Issues
Install App: app installed on your account

**Comment by mboussaa** [comment]
Yes as you mentioned, Here are screeshots of all configurations:
<img width="754" alt="Screenshot 2019-11-07 at 15 34 53" src="https://user-images.githubusercontent.com/5878565/68397895-2eba0b00-0174-11ea-9585-5a5109fbc1c6.png">
<img width="881" alt="Screenshot 2019-11-07 at 15 34 12" src="https://user-images.githubusercontent.com/5878565/68397896-2eba0b00-0174-11ea-96cf-123971437731.png">
<img width="1128" alt="Screenshot 2019-11-07 at 15 34 37" src="https://user-images.githubusercontent.com/5878565/68397897-2eba0b00-0174-11ea-9599-c29d0c9fc7f1.png">
![Screenshot 2019-11-07 at 15 30 14](https://user-images.githubusercontent.com/5878565/68397661-d7b43600-0173-11ea-9528-48e834bd616f.png)
![Screenshot 2019-11-07 at 15 30 29](https://user-images.githubusercontent.com/5878565/68397663-d84ccc80-0173-11ea-8d32-c311dd8422c7.png)
![Screenshot 2019-11-07 at 15 30 41](https://user-images.githubusercontent.com/5878565/68397664-d84ccc80-0173-11ea-94e0-acb3338073c6.png)
![Screenshot 2019-11-07 at 15 32 20](https://user-images.githubusercontent.com/5878565/68397666-d84ccc80-0173-11ea-9d92-c12577e825cf.png)

**Comment by luandrea** [comment]
I see a different URL published from ngrok from what you have configured on GitHub, can you check it?

**Comment by mboussaa** [comment]
Because I restarted the server to see if it fixes the problem. In the screenshot it is the old one but in my config I use the new one http://20483059.ngrok.io/botsing-server

**Comment by mboussaa** [comment]
and to add as Info, the token provided in application.properties is generated as in this screenshot:
<img width="1011" alt="Screenshot 2019-11-07 at 15 51 14" src="https://user-images.githubusercontent.com/5878565/68399298-7fcafe80-0176-11ea-9c83-11cc3c57f3f2.png">

**Comment by luandrea** [comment]
Ok, I see that the token have never been used.

Mine is like that:
![image](https://user-images.githubusercontent.com/1321508/68400180-e43a8d80-0177-11ea-886d-cf784451b1d4.png)

Can you check that the botsing-server can access the github repository?

Also, you don't need all those permissions, and it would be a good idea to revoke it since you have shared it here.

**Comment by mboussaa** [comment]
How can I check that? 
are you sure that this address is the correct one to give as webhook url http://643c3eb7.ngrok.io/botsing-server ? I don't see any endpoints with `/botsing-server`

**Comment by mboussaa** [comment]
The server is well up running as you can see here:
<img width="881" alt="Screenshot 2019-11-07 at 16 43 49" src="https://user-images.githubusercontent.com/5878565/68403807-d38d1600-017d-11ea-8df0-c65047fb887f.png">

**Comment by luandrea** [comment]
Can you try using http://643c3eb7.ngrok.io/botsing-github-app in the Webhook URL?

**Comment by mboussaa** [comment]
That is it. At least now, the app started to communicate with the server. Though, got `Invalid action opened for event issues`. I guess this happened when trying to send the Post request 
```
2019-11-07 16:29:46 - Started Application in 2.974 seconds (JVM running for 3.572)
2019-11-07 16:49:59 - 'issues' Event received
2019-11-07 16:49:59 - 'issues' Event received
2019-11-07 16:49:59 - Invalid action opened for event issues
```

**Comment by mboussaa** [comment]
the log message comes from this line of code https://github.com/STAMP-project/botsing-server/blob/master/src/main/java/eu/stamp/botsing/controller/github/GitHubAppController.java#L61
following an InvalidActionException. I just created a new issue in the target project https://github.com/mboussaa/Botsing-server-test/issues/9. @luandrea do you have any idea why is this happening?

**Comment by luandrea** [comment]
Ok, I have updated the README.md to make it more clear. If you have any suggestion on making it better let me know.

Now for that error can you try to add the botsing label to the issue?

**Comment by mboussaa** [comment]
Hello @luandrea 

Do you have any idea about that issue and are you going to consider to fix that InvalidActionException?  

About the readme, I'm going to send a PR to make it more clear and simple to follow.

For the botsing label, OK.

**Comment by luandrea** [comment]
Hi @mboussaa,
I think that the problem is that we have to make that exception more clear, and add some informations about why the event received from botsing-server is considered invalid and maybe a list of valid events. It is correct to reject a simple issue, althought every new issue will trigger botsing-server. For this reason, in the last changes, @cformisano added this condition.

Thank you very much for your feedback and I will wait for your PR to add also these last changes.

**Comment by mboussaa** [comment]
I create this PR to fix the guide steps https://github.com/STAMP-project/botsing-server/pull/6

**Comment by mboussaa** [comment]
For the exception, I don't know if you could reproduce the issue, or plan to fix it...

**Comment by cformisano** [comment]
Dear @mboussaa ,
hi have accepted your pull request including the fixes for the documentation and I have also included more information in the log (e.g. the list of "valid" actions).
I have already deployed the latest version on the test environment where it is up and running.
Please check and let me know if now it is OK
Kind Regards
Ciro

**Comment by mboussaa** [comment]
Hello @cformisano 
I am still facing the same issue below: 
> 14:56:35.975 [http-nio-3000-exec-9] DEBUG e.s.b.c.g.GitHubAppController - 'issues' Event received
> 14:56:35.977 [http-nio-3000-exec-9] DEBUG e.s.b.c.AppController - 'issues' Event received
> 14:56:35.988 [http-nio-3000-exec-9] DEBUG e.s.b.c.g.GitHubAppController - Invalid action opened for event issues in GitHub, valid actions: [labeled [filter: accepted label: ]]

**Comment by cformisano** [comment]
I have had a look at the version on the testbed (that is up-to date) and I did not see your log. Which instance are you using? Is it correctly configured?
Specifically you need to specify in the application.properties the parameter
'githubAcceptedLabel=botsing'

Looking at the readme file I see that it is not specified: I am going to fix it, however please, configure your instance as suggested and let me know.

**Comment by mboussaa** [comment]
I followed all steps as in the readme file
@cformisano My application.propoerties file is the following and still get the same issue. Is there anything wrong with these values? 
```
server.port=3000
application.pem-file=
application.app-id=

githubAcceptedLabel=botsing

# GitHub
githubOAuth2Token=MY_TOEKN
githubUsername=
githubPassword=
githubURL=

#Jira
jiraURL=
jiraUsername=
jiraPassword=


# Proxy
proxyHost=
proxyPort=
```

**Comment by cformisano** [comment]
sounds strange. Seems like two different version. Let's check to align: for this fix I did not change the version number, I will do it. I am defining a version 1.1.1 that I am going to push on GitHub, please use this one.

**Comment by mboussaa** [comment]
Changing the version does not fix the issue as I am doing mvn clean package everytime after fetch/pull.

**Comment by cformisano** [comment]
Very strange: please, double check the name of the file: I see that you copied the name "application.propoerties" (the correct spelling is application.properties.

**Comment by mboussaa** [comment]
that is because I wrote it quickly :D yes the file is located here: src/main/resources/application.properties

**Comment by cformisano** [comment]
in the deployment, is it located in the same directory of the jar file?

**Comment by mboussaa** [comment]
@cformisano I don't understand your question. Here is where my files are located:
-botsing-server/src/main/resources/application.properties
-botsing-server/target/botsing-server-1.1.1.jar
-SUT: https://github.com/mboussaa/Botsing-server-test

**Comment by cformisano** [comment]
@mboussaa , sorry for the late answer (I was ooo yesterday and the day before). 
In my opinion you cannot reach your application.properties file: please to use the java property -Dspring.config.location to point your application.properties file when you start your server. As an alternative put the jar and the application.properties file in the same directory or apply both the solutions at the same time (same directory and -Dspring.config.location option)

**Comment by mboussaa** [comment]
same issue

**Comment by cformisano** [comment]
OK. Since for me it is impossible to reproduce the issue I see two possibilities:
1) direct access to the VM on which you have deployed your instance

If (as I guess) this is not possible please:
2) let me know exactly all the information concerning the deployment, in particular:
             * relative path of all the files that concern the server (including log files, jar file, configuration file)
             * the command you use to start it
             * attach me also the log file. If it is too big, please delete it, reproduce the problem and attach the resulting file.

I will try to understand what is happened and I will return to you with a solution.

**Comment by mboussaa** [comment]
-java -jar botsing-server-1.1.1.jar --spring.config.location=/Users/mohamedboussaa/Documents/STAMP/botsing-server/src/main/resources/application.properties (also tested /Users/mohamedboussaa/Documents/STAMP/botsing-server/target/application.properties and also without --spring.config.location)
-Folder tree 
[tree.txt](https://github.com/STAMP-project/botsing-server/files/3880086/tree.txt)
-Logs:
```
2019-11-18 16:00:39 - Starting Application v1.1.1 on Marcos-MacBook-Pro.local with PID 7476 (/Users/mohamedboussaa/Documents/STAMP/botsing-server/target/botsing-server-1.1.1.jar started by mohamedboussaa in /Users/mohamedboussaa/Documents/STAMP/botsing-server)
2019-11-18 16:00:39 - Running with Spring Boot v2.1.0.RELEASE, Spring v5.1.2.RELEASE
2019-11-18 16:00:39 - No active profile set, falling back to default profiles: default
2019-11-18 16:00:42 - Temporary Store limit is 51200 mb, whilst the temporary data directory: /Users/mohamedboussaa/Documents/STAMP/botsing-server/activemq-data/localhost/tmp_storage only has 18635 mb of usable space
2019-11-18 16:00:43 - Started Application in 5.289 seconds (JVM running for 6.062)
2019-11-18 16:02:38 - 'issues' Event received
2019-11-18 16:02:38 - 'issues' Event received
2019-11-18 16:02:38 - Invalid action opened for event issues in GitHub, valid actions: [labeled [filter: accepted label: botsing]]

```

**Comment by cformisano** [comment]
thank you very much, now it is clear.
First of all: the log appears different to what you indicated previously:

> 2019-11-18 16:02:38 - Invalid action opened for event issues in GitHub, valid actions: [labeled [filter: accepted label: botsing]]

now indicates the correct label "botsing", so this is OK.

Furthermore the option 

> --spring.config.location=/Users/mohamedboussaa/Documents/STAMP/botsing-server/src/main/resources/application.properties

is not correct, you should use 

> -Dspring.config.location=/Users/mohamedboussaa/Documents/STAMP/botsing-server/src/main/resources/application.properties

however I think that it should not be necessary since the log is OK now (and that option is not taken into account by the app)

If you want to start botsing you have to define a label "botsing" (lowercase not "Botsing") and use it.

Please, let me know if it works now.

**Comment by mboussaa** [comment]
ouf that is it. I didn't add the label. It was not mentioned in the tutorial though.
here's the SUT: https://github.com/mboussaa/Botsing-server-test/issues/17
Here's new logs + issue:
```

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.0.RELEASE)

16:23:19.446 [main] INFO  e.s.b.Application - Starting Application v1.1.1 on Marcos-MacBook-Pro.local with PID 47278 (/Users/mohamedboussaa/Documents/STAMP/botsing-server/target/botsing-server-1.1.1.jar started by mohamedboussaa in /Users/mohamedboussaa/Documents/STAMP/botsing-server/target)
16:23:19.450 [main] DEBUG e.s.b.Application - Running with Spring Boot v2.1.0.RELEASE, Spring v5.1.2.RELEASE
16:23:19.452 [main] INFO  e.s.b.Application - No active profile set, falling back to default profiles: default
16:23:21.879 [main] ERROR o.a.a.b.BrokerService - Temporary Store limit is 51200 mb, whilst the temporary data directory: /Users/mohamedboussaa/Documents/STAMP/botsing-server/target/activemq-data/localhost/tmp_storage only has 12195 mb of usable space
16:23:22.434 [main] INFO  e.s.b.Application - Started Application in 3.579 seconds (JVM running for 4.431)
16:27:26.196 [http-nio-3000-exec-2] DEBUG e.s.b.c.g.GitHubAppController - 'issues' Event received
16:27:26.196 [http-nio-3000-exec-1] DEBUG e.s.b.c.g.GitHubAppController - 'issues' Event received
16:27:26.196 [http-nio-3000-exec-1] DEBUG e.s.b.c.AppController - 'issues' Event received
16:27:26.196 [http-nio-3000-exec-2] DEBUG e.s.b.c.AppController - 'issues' Event received
16:27:26.208 [http-nio-3000-exec-1] DEBUG e.s.b.c.e.f.g.GitHubConfigurationBasedChangeLabelActionFilter - Added Label botsing
16:27:26.208 [http-nio-3000-exec-2] DEBUG e.s.b.c.g.GitHubAppController - Invalid action opened for event issues in GitHub, valid actions: [labeled [filter: accepted label: botsing]]
16:27:26.208 [http-nio-3000-exec-1] DEBUG e.s.b.c.QueuedAppController - Action found: publishing on the queue
16:27:26.208 [http-nio-3000-exec-1] DEBUG e.s.b.c.q.QueuePublisher - Adding the request in queue
16:27:26.234 [Thread-6] DEBUG e.s.b.c.e.f.g.GitHubConfigurationBasedChangeLabelActionFilter - Added Label botsing
16:27:26.236 [Thread-6] DEBUG e.s.b.c.e.g.GitHubDataManager - Reading file '.botsing'
16:27:27.381 [Thread-6] DEBUG e.s.b.c.e.g.GitHubDataManager - File '.botsing' read
16:27:27.382 [Thread-6] DEBUG e.s.b.c.e.g.GitHubNotificationClient - Creating comment
16:27:27.925 [Thread-6] DEBUG e.s.b.c.e.g.GitHubNotificationClient - Issue comment created
16:27:27.938 [Thread-6] DEBUG e.s.b.c.e.a.BotsingExecutor - Running botsing...
16:27:33.510 [Thread-6] DEBUG e.s.b.r.MavenRunner - Process exited with result 1, output [INFO] Scanning for projects...
Downloading from central: https://repo.maven.apache.org/maven2/eu/stamp-project/botsing-maven/maven-metadata.xml
Progress (1): 522 B

Downloaded from central: https://repo.maven.apache.org/maven2/eu/stamp-project/botsing-maven/maven-metadata.xml (522 B at 1.4 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/eu/stamp-project/botsing-maven/1.0.7/botsing-maven-1.0.7.pom
Progress (1): 1.4/3.5 kB
Progress (1): 2.7/3.5 kB
Progress (1): 3.5 kB

Downloaded from central: https://repo.maven.apache.org/maven2/eu/stamp-project/botsing-maven/1.0.7/botsing-maven-1.0.7.pom (3.5 kB at 12 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/eu/stamp-project/botsing/1.0.7/botsing-1.0.7.pom
Progress (1): 1.4/22 kB
Progress (1): 2.7/22 kB
Progress (1): 4.1/22 kB
Progress (1): 5.5/22 kB
Progress (1): 6.9/22 kB
Progress (1): 8.2/22 kB
Progress (1): 9.6/22 kB
Progress (1): 11/22 kB
Progress (1): 12/22 kB
Progress (1): 14/22 kB
Progress (1): 15/22 kB
Progress (1): 16/22 kB
Progress (1): 18/22 kB
Progress (1): 19/22 kB
Progress (1): 21/22 kB
Progress (1): 22/22 kB
Progress (1): 22 kB

Downloaded from central: https://repo.maven.apache.org/maven2/eu/stamp-project/botsing/1.0.7/botsing-1.0.7.pom (22 kB at 65 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/eu/stamp-project/botsing-maven/1.0.7/botsing-maven-1.0.7.jar
Progress (1): 1.4/43 kB
Progress (1): 2.7/43 kB
Progress (1): 4.1/43 kB
Progress (1): 5.5/43 kB
Progress (1): 6.9/43 kB
Progress (1): 8.2/43 kB
Progress (1): 9.6/43 kB
Progress (1): 11/43 kB
Progress (1): 12/43 kB
Progress (1): 14/43 kB
Progress (1): 15/43 kB
Progress (1): 16/43 kB
Progress (1): 18/43 kB
Progress (1): 19/43 kB
Progress (1): 21/43 kB
Progress (1): 22/43 kB
Progress (1): 23/43 kB
Progress (1): 25/43 kB
Progress (1): 26/43 kB
Progress (1): 27/43 kB
Progress (1): 29/43 kB
Progress (1): 30/43 kB
Progress (1): 32/43 kB
Progress (1): 33/43 kB
Progress (1): 34/43 kB
Progress (1): 36/43 kB
Progress (1): 37/43 kB
Progress (1): 38/43 kB
Progress (1): 40/43 kB
Progress (1): 41/43 kB
Progress (1): 43/43 kB
Progress (1): 43 kB

Downloaded from central: https://repo.maven.apache.org/maven2/eu/stamp-project/botsing-maven/1.0.7/botsing-maven-1.0.7.jar (43 kB at 129 kB/s)
[INFO]
[INFO] -----------< eu.stamp-project:botsing-maven-working-project >-----------
[INFO] Building Project to run Botsing Maven 1.0.0-SNAPSHOT
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- botsing-maven:1.0.7:botsing (default-cli) @ botsing-maven-working-project ---
[INFO] Starting Botsing to generate tests with EvoSuite
Downloading from central: https://repo.maven.apache.org/maven2/eu/stamp-project/botsing-preprocessing/maven-metadata.xml
Progress (1): 530 B

Downloaded from central: https://repo.maven.apache.org/maven2/eu/stamp-project/botsing-preprocessing/maven-metadata.xml (530 B at 5.7 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/eu/stamp-project/botsing-preprocessing/1.0.7/botsing-preprocessing-1.0.7-jar-with-dependencies.jar
Progress (1): 1.4/65 kB
Progress (1): 2.7/65 kB
Progress (1): 4.1/65 kB
Progress (1): 5.5/65 kB
Progress (1): 6.9/65 kB
Progress (1): 8.2/65 kB
Progress (1): 9.6/65 kB
Progress (1): 11/65 kB
Progress (1): 12/65 kB
Progress (1): 14/65 kB
Progress (1): 15/65 kB
Progress (1): 16/65 kB
Progress (1): 18/65 kB
Progress (1): 19/65 kB
Progress (1): 21/65 kB
Progress (1): 22/65 kB
Progress (1): 23/65 kB
Progress (1): 25/65 kB
Progress (1): 26/65 kB
Progress (1): 27/65 kB
Progress (1): 29/65 kB
Progress (1): 30/65 kB
Progress (1): 32/65 kB
Progress (1): 33/65 kB
Progress (1): 34/65 kB
Progress (1): 36/65 kB
Progress (1): 37/65 kB
Progress (1): 38/65 kB
Progress (1): 40/65 kB
Progress (1): 41/65 kB
Progress (1): 43/65 kB
Progress (1): 44/65 kB
Progress (1): 45/65 kB
Progress (1): 47/65 kB
Progress (1): 48/65 kB
Progress (1): 49/65 kB
Progress (1): 51/65 kB
Progress (1): 52/65 kB
Progress (1): 53/65 kB
Progress (1): 55/65 kB
Progress (1): 56/65 kB
Progress (1): 58/65 kB
Progress (1): 59/65 kB
Progress (1): 60/65 kB
Progress (1): 62/65 kB
Progress (1): 63/65 kB
Progress (1): 64/65 kB
Progress (1): 65 kB

Downloaded from central: https://repo.maven.apache.org/maven2/eu/stamp-project/botsing-preprocessing/1.0.7/botsing-preprocessing-1.0.7-jar-with-dependencies.jar (65 kB at 225 kB/s)
[INFO] End pre-processing
[INFO] Reading dependencies from artifact
[INFO] Collected dependencies: /Users/mohamedboussaa/.m2/repository/org/ow2/authzforce/authzforce-ce-core-pdp-testutils/13.3.1/authzforce-ce-core-pdp-testutils-13.3.1.jar:/Users/mohamedboussaa/.m2/repository/org/ow2/authzforce/authzforce-ce-core-pdp-engine/13.3.1/authzforce-ce-core-pdp-engine-13.3.1.jar:/Users/mohamedboussaa/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.25/jcl-over-slf4j-1.7.25.jar:/Users/mohamedboussaa/.m2/repository/com/sun/mail/javax.mail/1.6.0/javax.mail-1.6.0.jar:/Users/mohamedboussaa/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar:/Users/mohamedboussaa/.m2/repository/org/springframework/spring-core/4.3.20.RELEASE/spring-core-4.3.20.RELEASE.jar:/Users/mohamedboussaa/.m2/repository/xml-resolver/xml-resolver/1.2/xml-resolver-1.2.jar:/Users/mohamedboussaa/.m2/repository/org/ow2/authzforce/authzforce-ce-core-pdp-api/15.3.0/authzforce-ce-core-pdp-api-15.3.0.jar:/Users/mohamedboussaa/.m2/repository/net/sf/saxon/Saxon-HE/9.8.0-12/Saxon-HE-9.8.0-12.jar:/Users/mohamedboussaa/.m2/repository/javax/mail/javax.mail-api/1.6.0/javax.mail-api-1.6.0.jar:/Users/mohamedboussaa/.m2/repository/com/google/guava/guava/24.1.1-jre/guava-24.1.1-jre.jar:/Users/mohamedboussaa/.m2/repository/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar:/Users/mohamedboussaa/.m2/repository/org/checkerframework/checker-compat-qual/2.0.0/checker-compat-qual-2.0.0.jar:/Users/mohamedboussaa/.m2/repository/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.jar:/Users/mohamedboussaa/.m2/repository/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar:/Users/mohamedboussaa/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.jar:/Users/mohamedboussaa/.m2/repository/org/ow2/authzforce/authzforce-ce-xacml-model/7.5.1/authzforce-ce-xacml-model-7.5.1.jar:/Users/mohamedboussaa/.m2/repository/org/ow2/authzforce/authzforce-ce-xmlns-model/7.5.1/authzforce-ce-xmlns-model-7.5.1.jar:/Users/mohamedboussaa/.m2/repository/org/jvnet/jaxb2_commons/jaxb2-basics-runtime/1.11.1/jaxb2-basics-runtime-1.11.1.jar:/Users/mohamedboussaa/.m2/repository/org/ow2/authzforce/authzforce-ce-pdp-ext-model/7.5.1/authzforce-ce-pdp-ext-model-7.5.1.jar:/Users/mohamedboussaa/.m2/repository/org/mongodb/mongo-java-driver/3.5.0/mongo-java-driver-3.5.0.jar:/Users/mohamedboussaa/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.9.8/jackson-databind-2.9.8.jar:/Users/mohamedboussaa/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.9.0/jackson-annotations-2.9.0.jar:/Users/mohamedboussaa/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.9.8/jackson-core-2.9.8.jar:/Users/mohamedboussaa/.m2/repository/org/jongo/jongo/1.4.0/jongo-1.4.0.jar:/Users/mohamedboussaa/.m2/repository/de/undercouch/bson4jackson/2.9.0/bson4jackson-2.9.0.jar:/Users/mohamedboussaa/.m2/repository/junit/junit/4.11/junit-4.11.jar:/Users/mohamedboussaa/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/Users/mohamedboussaa/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar:/Users/mohamedboussaa/.m2/repository/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar:/Users/mohamedboussaa/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar:/Users/mohamedboussaa/.m2/repository/org/apache/cxf/cxf-rt-frontend-jaxws/3.2.5/cxf-rt-frontend-jaxws-3.2.5.jar:/Users/mohamedboussaa/.m2/repository/org/ow2/asm/asm/5.2/asm-5.2.jar:/Users/mohamedboussaa/.m2/repository/org/apache/cxf/cxf-core/3.2.5/cxf-core-3.2.5.jar:/Users/mohamedboussaa/.m2/repository/com/fasterxml/woodstox/woodstox-core/5.0.3/woodstox-core-5.0.3.jar:/Users/mohamedboussaa/.m2/repository/org/codehaus/woodstox/stax2-api/3.1.4/stax2-api-3.1.4.jar:/Users/mohamedboussaa/.m2/repository/org/apache/ws/xmlschema/xmlschema-core/2.2.3/xmlschema-core-2.2.3.jar:/Users/mohamedboussaa/.m2/repository/org/apache/cxf/cxf-rt-bindings-soap/3.2.5/cxf-rt-bindings-soap-3.2.5.jar:/Users/mohamedboussaa/.m2/repository/org/apache/cxf/cxf-rt-databinding-jaxb/3.2.5/cxf-rt-databinding-jaxb-3.2.5.jar:/Users/mohamedboussaa/.m2/repository/org/apache/cxf/cxf-rt-bindings-xml/3.2.5/cxf-rt-bindings-xml-3.2.5.jar:/Users/mohamedboussaa/.m2/repository/org/apache/cxf/cxf-rt-frontend-simple/3.2.5/cxf-rt-frontend-simple-3.2.5.jar:/Users/mohamedboussaa/.m2/repository/org/apache/cxf/cxf-rt-ws-addr/3.2.5/cxf-rt-ws-addr-3.2.5.jar:/Users/mohamedboussaa/.m2/repository/org/apache/cxf/cxf-rt-ws-policy/3.2.5/cxf-rt-ws-policy-3.2.5.jar:/Users/mohamedboussaa/.m2/repository/org/apache/neethi/neethi/3.1.1/neethi-3.1.1.jar:/Users/mohamedboussaa/.m2/repository/org/apache/cxf/cxf-rt-transports-http-jetty/3.2.5/cxf-rt-transports-http-jetty-3.2.5.jar:/Users/mohamedboussaa/.m2/repository/org/apache/cxf/cxf-rt-transports-http/3.2.5/cxf-rt-transports-http-3.2.5.jar:/Users/mohamedboussaa/.m2/repository/org/eclipse/jetty/jetty-server/9.4.11.v20180605/jetty-server-9.4.11.v20180605.jar:/Users/mohamedboussaa/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar:/Users/mohamedboussaa/.m2/repository/org/eclipse/jetty/jetty-util/9.4.11.v20180605/jetty-util-9.4.11.v20180605.jar:/Users/mohamedboussaa/.m2/repository/org/eclipse/jetty/jetty-io/9.4.11.v20180605/jetty-io-9.4.11.v20180605.jar:/Users/mohamedboussaa/.m2/repository/org/eclipse/jetty/jetty-security/9.4.11.v20180605/jetty-security-9.4.11.v20180605.jar:/Users/mohamedboussaa/.m2/repository/org/eclipse/jetty/jetty-continuation/9.4.11.v20180605/jetty-continuation-9.4.11.v20180605.jar:/Users/mohamedboussaa/.m2/repository/org/eclipse/jetty/jetty-http/9.4.11.v20180605/jetty-http-9.4.11.v20180605.jar:/Users/mohamedboussaa/.m2/repository/org/apache/cxf/services/sts/cxf-services-sts-core/3.2.5/cxf-services-sts-core-3.2.5.jar:/Users/mohamedboussaa/.m2/repository/org/apache/cxf/cxf-rt-ws-security/3.2.5/cxf-rt-ws-security-3.2.5.jar:/Users/mohamedboussaa/.m2/repository/org/apache/cxf/cxf-rt-security-saml/3.2.5/cxf-rt-security-saml-3.2.5.jar:/Users/mohamedboussaa/.m2/repository/net/sf/ehcache/ehcache/2.10.5/ehcache-2.10.5.jar:/Users/mohamedboussaa/.m2/repository/org/apache/wss4j/wss4j-ws-security-dom/2.2.2/wss4j-ws-security-dom-2.2.2.jar:/Users/mohamedboussaa/.m2/repository/org/apache/wss4j/wss4j-ws-security-common/2.2.2/wss4j-ws-security-common-2.2.2.jar:/Users/mohamedboussaa/.m2/repository/org/apache/santuario/xmlsec/2.1.2/xmlsec-2.1.2.jar:/Users/mohamedboussaa/.m2/repository/commons-codec/commons-codec/1.11/commons-codec-1.11.jar:/Users/mohamedboussaa/.m2/repository/org/opensaml/opensaml-saml-impl/3.3.0/opensaml-saml-impl-3.3.0.jar:/Users/mohamedboussaa/.m2/repository/org/opensaml/opensaml-profile-api/3.3.0/opensaml-profile-api-3.3.0.jar:/Users/mohamedboussaa/.m2/repository/org/opensaml/opensaml-core/3.3.0/opensaml-core-3.3.0.jar:/Users/mohamedboussaa/.m2/repository/io/dropwizard/metrics/metrics-core/3.1.2/metrics-core-3.1.2.jar:/Users/mohamedboussaa/.m2/repository/org/opensaml/opensaml-saml-api/3.3.0/opensaml-saml-api-3.3.0.jar:/Users/mohamedboussaa/.m2/repository/org/opensaml/opensaml-xmlsec-api/3.3.0/opensaml-xmlsec-api-3.3.0.jar:/Users/mohamedboussaa/.m2/repository/org/opensaml/opensaml-soap-api/3.3.0/opensaml-soap-api-3.3.0.jar:/Users/mohamedboussaa/.m2/repository/org/opensaml/opensaml-security-impl/3.3.0/opensaml-security-impl-3.3.0.jar:/Users/mohamedboussaa/.m2/repository/org/opensaml/opensaml-security-api/3.3.0/opensaml-security-api-3.3.0.jar:/Users/mohamedboussaa/.m2/repository/org/cryptacular/cryptacular/1.1.1/cryptacular-1.1.1.jar:/Users/mohamedboussaa/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.54/bcprov-jdk15on-1.54.jar:/Users/mohamedboussaa/.m2/repository/org/opensaml/opensaml-xmlsec-impl/3.3.0/opensaml-xmlsec-impl-3.3.0.jar:/Users/mohamedboussaa/.m2/repository/net/shibboleth/utilities/java-support/7.3.0/java-support-7.3.0.jar:/Users/mohamedboussaa/.m2/repository/joda-time/joda-time/2.9/joda-time-2.9.jar:/Users/mohamedboussaa/.m2/repository/org/opensaml/opensaml-xacml-impl/3.3.0/opensaml-xacml-impl-3.3.0.jar:/Users/mohamedboussaa/.m2/repository/org/opensaml/opensaml-xacml-api/3.3.0/opensaml-xacml-api-3.3.0.jar:/Users/mohamedboussaa/.m2/repository/org/opensaml/opensaml-xacml-saml-impl/3.3.0/opensaml-xacml-saml-impl-3.3.0.jar:/Users/mohamedboussaa/.m2/repository/org/opensaml/opensaml-xacml-saml-api/3.3.0/opensaml-xacml-saml-api-3.3.0.jar:/Users/mohamedboussaa/.m2/repository/org/jasypt/jasypt/1.9.2/jasypt-1.9.2.jar:/Users/mohamedboussaa/.m2/repository/org/apache/wss4j/wss4j-policy/2.2.2/wss4j-policy-2.2.2.jar:/Users/mohamedboussaa/.m2/repository/org/apache/wss4j/wss4j-ws-security-stax/2.2.2/wss4j-ws-security-stax-2.2.2.jar:/Users/mohamedboussaa/.m2/repository/org/apache/wss4j/wss4j-bindings/2.2.2/wss4j-bindings-2.2.2.jar:/Users/mohamedboussaa/.m2/repository/org/apache/wss4j/wss4j-ws-security-policy-stax/2.2.2/wss4j-ws-security-policy-stax-2.2.2.jar:/Users/mohamedboussaa/.m2/repository/org/apache/cxf/cxf-rt-rs-security-jose/3.2.5/cxf-rt-rs-security-jose-3.2.5.jar:/Users/mohamedboussaa/.m2/repository/org/apache/cxf/cxf-rt-security/3.2.5/cxf-rt-security-3.2.5.jar:/Users/mohamedboussaa/.m2/repository/org/apache/cxf/cxf-rt-rs-json-basic/3.2.5/cxf-rt-rs-json-basic-3.2.5.jar:/Users/mohamedboussaa/.m2/repository/org/springframework/spring-context/4.3.20.RELEASE/spring-context-4.3.20.RELEASE.jar:/Users/mohamedboussaa/.m2/repository/org/springframework/spring-aop/4.3.20.RELEASE/spring-aop-4.3.20.RELEASE.jar:/Users/mohamedboussaa/.m2/repository/org/springframework/spring-beans/4.3.20.RELEASE/spring-beans-4.3.20.RELEASE.jar:/Users/mohamedboussaa/.m2/repository/org/springframework/spring-expression/4.3.20.RELEASE/spring-expression-4.3.20.RELEASE.jar:/Users/mohamedboussaa/.m2/repository/org/apache/cxf/cxf-testutils/3.2.5/cxf-testutils-3.2.5.jar:/Users/mohamedboussaa/.m2/repository/org/apache/cxf/cxf-rt-wsdl/3.2.5/cxf-rt-wsdl-3.2.5.jar:/Users/mohamedboussaa/.m2/repository/wsdl4j/wsdl4j/1.6.3/wsdl4j-1.6.3.jar:/Users/mohamedboussaa/.m2/repository/org/apache/geronimo/javamail/geronimo-javamail_1.4_mail/1.8.4/geronimo-javamail_1.4_mail-1.8.4.jar:/Users/mohamedboussaa/.m2/repository/de/bwaldvogel/mongo-java-server/1.7.0/mongo-java-server-1.7.0.jar:/Users/mohamedboussaa/.m2/repository/de/bwaldvogel/mongo-java-server-core/1.7.0/mongo-java-server-core-1.7.0.jar:/Users/mohamedboussaa/.m2/repository/io/netty/netty-transport/4.1.9.Final/netty-transport-4.1.9.Final.jar:/Users/mohamedboussaa/.m2/repository/io/netty/netty-buffer/4.1.9.Final/netty-buffer-4.1.9.Final.jar:/Users/mohamedboussaa/.m2/repository/io/netty/netty-common/4.1.9.Final/netty-common-4.1.9.Final.jar:/Users/mohamedboussaa/.m2/repository/io/netty/netty-resolver/4.1.9.Final/netty-resolver-4.1.9.Final.jar:/Users/mohamedboussaa/.m2/repository/io/netty/netty-codec/4.1.9.Final/netty-codec-4.1.9.Final.jar:/Users/mohamedboussaa/.m2/repository/de/bwaldvogel/mongo-java-server-memory-backend/1.7.0/mongo-java-server-memory-backend-1.7.0.jar:
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.180 s
[INFO] Finished at: 2019-11-22T16:27:33+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal eu.stamp-project:botsing-maven:1.0.7:botsing (default-cli) on project botsing-maven-working-project: Execution default-cli of goal eu.stamp-project:botsing-maven:1.0.7:botsing failed.: NullPointerException -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

16:27:33.515 [Thread-6] DEBUG e.s.b.c.e.a.BotsingExecutor - Botsing execution completed with result FAIL
16:27:33.516 [Thread-6] DEBUG e.s.b.c.e.g.i.GitHubIssuesActionBotsing - Botsing executed with result FAIL
16:27:33.516 [Thread-6] DEBUG e.s.b.c.e.g.GitHubNotificationClient - Creating comment
16:27:34.645 [Thread-6] DEBUG e.s.b.c.e.g.GitHubNotificationClient - Issue comment created
```

**Comment by cformisano** [comment]
Dear Mohamed, 
I have updated the Readme of Botsing Server, now it should be clearer. Concerning the error you have shown, it does not seem to concern Botsing Server since the Service correctly forward the request to Botsing. 
However I performed some tests, both on my instance of Botsing Server and by using Botsing Maven and it correctly produce the test files.
As a suggestion, please, have a look at your .botsing file to check if the parameters (Group-Artifact-Version) are appropriate for your application.

**Comment by mboussaa** [comment]
Thank you for your reply. Here is the link for .botsing https://github.com/mboussaa/Botsing-server-test/blob/master/.botsing

**Comment by cformisano** [comment]
It is identical to the mine. 
First of all, please check again: maybe it has been a temporary problem at maven side... possible.
If it does not work, let's proceed step by step, let's check botsing-maven. Please try on your machine and, possible, on the machine on which you installed botsing-server, to run botsing locally. You can proceed in the following way:
1) copy the stack trace on a text file called stacktrace.log in a folder
2) in the same folder create a pom file identical to the attached one (I have replaced the .xml extension with a .txt to upload it, please return to the original extension)
[pom.txt](https://github.com/STAMP-project/botsing-server/files/3887725/pom.txt)
3) in the same folder start bosting-maven by the following command:
`
mvn eu.stamp-project:botsing-maven:botsing -Dcrash_log=stacktrace.log -Dmax_target_frame=2 -Dgroup_id=org.ow2.authzforce -Dartifact_id=authzforce-ce-core-pdp-testutils -Dversion=13.3.1
`
Please, let me know if the test files are produced on your machine and on the machine on which you installed botsing-server.
Please note that you do not need to install anything but maven to work.

**Comment by mboussaa** [comment]
I get this:
> (base) Marcos-MacBook-Pro:botsing-maven mohamedboussaa$ mvn eu.stamp-project:botsing-maven:botsing -Dcrash_log=stacktrace.log -Dmax_target_frame=2 -Dgroup_id=org.ow2.authzforce -Dartifact_id=authzforce-ce-core-pdp-testutils -Dversion=13.3.1
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for eu.stamp-project:botsing-maven:maven-plugin:1.0.8-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.eluder.coveralls:coveralls-maven-plugin is missing. @ eu.stamp-project:botsing:1.0.8-SNAPSHOT, /Users/mohamedboussaa/Documents/STAMP/botsing-server/botsing/pom.xml, line 272, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] -------------------< eu.stamp-project:botsing-maven >-------------------
[INFO] Building Botsing Maven Plugin 1.0.8-SNAPSHOT
[INFO] ----------------------------[ maven-plugin ]----------------------------
[INFO]
[INFO] --- botsing-maven:1.0.7:botsing (default-cli) @ botsing-maven ---
[INFO] Starting Botsing to generate tests with EvoSuite
[INFO] Wrong arguments. Input file name 'stacktrace.log' does not exist!
[INFO] Reading dependencies from artifact
[INFO] Collected dependencies: /Users/mohamedboussaa/.m2/repository/org/ow2/authzforce/authzforce-ce-core-pdp-testutils/13.3.1/authzforce-ce-core-pdp-testutils-13.3.1.jar:/Users/mohamedboussaa/.m2/repository/org/ow2/authzforce/authzforce-ce-core-pdp-engine/13.3.1/authzforce-ce-core-pdp-engine-13.3.1.jar:/Users/mohamedboussaa/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.25/jcl-over-slf4j-1.7.25.jar:/Users/mohamedboussaa/.m2/repository/com/sun/mail/javax.mail/1.6.0/javax.mail-1.6.0.jar:/Users/mohamedboussaa/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar:/Users/mohamedboussaa/.m2/repository/org/springframework/spring-core/4.3.20.RELEASE/spring-core-4.3.20.RELEASE.jar:/Users/mohamedboussaa/.m2/repository/xml-resolver/xml-resolver/1.2/xml-resolver-1.2.jar:/Users/mohamedboussaa/.m2/repository/org/ow2/authzforce/authzforce-ce-core-pdp-api/15.3.0/authzforce-ce-core-pdp-api-15.3.0.jar:/Users/mohamedboussaa/.m2/repository/net/sf/saxon/Saxon-HE/9.8.0-12/Saxon-HE-9.8.0-12.jar:/Users/mohamedboussaa/.m2/repository/javax/mail/javax.mail-api/1.6.0/javax.mail-api-1.6.0.jar:/Users/mohamedboussaa/.m2/repository/com/google/guava/guava/24.1.1-jre/guava-24.1.1-jre.jar:/Users/mohamedboussaa/.m2/repository/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar:/Users/mohamedboussaa/.m2/repository/org/checkerframework/checker-compat-qual/2.0.0/checker-compat-qual-2.0.0.jar:/Users/mohamedboussaa/.m2/repository/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.jar:/Users/mohamedboussaa/.m2/repository/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar:/Users/mohamedboussaa/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.jar:/Users/mohamedboussaa/.m2/repository/org/ow2/authzforce/authzforce-ce-xacml-model/7.5.1/authzforce-ce-xacml-model-7.5.1.jar:/Users/mohamedboussaa/.m2/repository/org/ow2/authzforce/authzforce-ce-xmlns-model/7.5.1/authzforce-ce-xmlns-model-7.5.1.jar:/Users/mohamedboussaa/.m2/repository/org/jvnet/jaxb2_commons/jaxb2-basics-runtime/1.11.1/jaxb2-basics-runtime-1.11.1.jar:/Users/mohamedboussaa/.m2/repository/org/ow2/authzforce/authzforce-ce-pdp-ext-model/7.5.1/authzforce-ce-pdp-ext-model-7.5.1.jar:/Users/mohamedboussaa/.m2/repository/org/mongodb/mongo-java-driver/3.5.0/mongo-java-driver-3.5.0.jar:/Users/mohamedboussaa/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.9.8/jackson-databind-2.9.8.jar:/Users/mohamedboussaa/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.9.0/jackson-annotations-2.9.0.jar:/Users/mohamedboussaa/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.9.8/jackson-core-2.9.8.jar:/Users/mohamedboussaa/.m2/repository/org/jongo/jongo/1.4.0/jongo-1.4.0.jar:/Users/mohamedboussaa/.m2/repository/de/undercouch/bson4jackson/2.9.0/bson4jackson-2.9.0.jar:/Users/mohamedboussaa/.m2/repository/junit/junit/4.11/junit-4.11.jar:/Users/mohamedboussaa/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/Users/mohamedboussaa/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar:/Users/mohamedboussaa/.m2/repository/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar:/Users/mohamedboussaa/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar:/Users/mohamedboussaa/.m2/repository/org/apache/cxf/cxf-rt-frontend-jaxws/3.2.5/cxf-rt-frontend-jaxws-3.2.5.jar:/Users/mohamedboussaa/.m2/repository/org/ow2/asm/asm/5.2/asm-5.2.jar:/Users/mohamedboussaa/.m2/repository/org/apache/cxf/cxf-core/3.2.5/cxf-core-3.2.5.jar:/Users/mohamedboussaa/.m2/repository/com/fasterxml/woodstox/woodstox-core/5.0.3/woodstox-core-5.0.3.jar:/Users/mohamedboussaa/.m2/repository/org/codehaus/woodstox/stax2-api/3.1.4/stax2-api-3.1.4.jar:/Users/mohamedboussaa/.m2/repository/org/apache/ws/xmlschema/xmlschema-core/2.2.3/xmlschema-core-2.2.3.jar:/Users/mohamedboussaa/.m2/repository/org/apache/cxf/cxf-rt-bindings-soap/3.2.5/cxf-rt-bindings-soap-3.2.5.jar:/Users/mohamedboussaa/.m2/repository/org/apache/cxf/cxf-rt-databinding-jaxb/3.2.5/cxf-rt-databinding-jaxb-3.2.5.jar:/Users/mohamedboussaa/.m2/repository/org/apache/cxf/cxf-rt-bindings-xml/3.2.5/cxf-rt-bindings-xml-3.2.5.jar:/Users/mohamedboussaa/.m2/repository/org/apache/cxf/cxf-rt-frontend-simple/3.2.5/cxf-rt-frontend-simple-3.2.5.jar:/Users/mohamedboussaa/.m2/repository/org/apache/cxf/cxf-rt-ws-addr/3.2.5/cxf-rt-ws-addr-3.2.5.jar:/Users/mohamedboussaa/.m2/repository/org/apache/cxf/cxf-rt-ws-policy/3.2.5/cxf-rt-ws-policy-3.2.5.jar:/Users/mohamedboussaa/.m2/repository/org/apache/neethi/neethi/3.1.1/neethi-3.1.1.jar:/Users/mohamedboussaa/.m2/repository/org/apache/cxf/cxf-rt-transports-http-jetty/3.2.5/cxf-rt-transports-http-jetty-3.2.5.jar:/Users/mohamedboussaa/.m2/repository/org/apache/cxf/cxf-rt-transports-http/3.2.5/cxf-rt-transports-http-3.2.5.jar:/Users/mohamedboussaa/.m2/repository/org/eclipse/jetty/jetty-server/9.4.11.v20180605/jetty-server-9.4.11.v20180605.jar:/Users/mohamedboussaa/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar:/Users/mohamedboussaa/.m2/repository/org/eclipse/jetty/jetty-util/9.4.11.v20180605/jetty-util-9.4.11.v20180605.jar:/Users/mohamedboussaa/.m2/repository/org/eclipse/jetty/jetty-io/9.4.11.v20180605/jetty-io-9.4.11.v20180605.jar:/Users/mohamedboussaa/.m2/repository/org/eclipse/jetty/jetty-security/9.4.11.v20180605/jetty-security-9.4.11.v20180605.jar:/Users/mohamedboussaa/.m2/repository/org/eclipse/jetty/jetty-continuation/9.4.11.v20180605/jetty-continuation-9.4.11.v20180605.jar:/Users/mohamedboussaa/.m2/repository/org/eclipse/jetty/jetty-http/9.4.11.v20180605/jetty-http-9.4.11.v20180605.jar:/Users/mohamedboussaa/.m2/repository/org/apache/cxf/services/sts/cxf-services-sts-core/3.2.5/cxf-services-sts-core-3.2.5.jar:/Users/mohamedboussaa/.m2/repository/org/apache/cxf/cxf-rt-ws-security/3.2.5/cxf-rt-ws-security-3.2.5.jar:/Users/mohamedboussaa/.m2/repository/org/apache/cxf/cxf-rt-security-saml/3.2.5/cxf-rt-security-saml-3.2.5.jar:/Users/mohamedboussaa/.m2/repository/net/sf/ehcache/ehcache/2.10.5/ehcache-2.10.5.jar:/Users/mohamedboussaa/.m2/repository/org/apache/wss4j/wss4j-ws-security-dom/2.2.2/wss4j-ws-security-dom-2.2.2.jar:/Users/mohamedboussaa/.m2/repository/org/apache/wss4j/wss4j-ws-security-common/2.2.2/wss4j-ws-security-common-2.2.2.jar:/Users/mohamedboussaa/.m2/repository/org/apache/santuario/xmlsec/2.1.2/xmlsec-2.1.2.jar:/Users/mohamedboussaa/.m2/repository/commons-codec/commons-codec/1.11/commons-codec-1.11.jar:/Users/mohamedboussaa/.m2/repository/org/opensaml/opensaml-saml-impl/3.3.0/opensaml-saml-impl-3.3.0.jar:/Users/mohamedboussaa/.m2/repository/org/opensaml/opensaml-profile-api/3.3.0/opensaml-profile-api-3.3.0.jar:/Users/mohamedboussaa/.m2/repository/org/opensaml/opensaml-core/3.3.0/opensaml-core-3.3.0.jar:/Users/mohamedboussaa/.m2/repository/io/dropwizard/metrics/metrics-core/3.1.2/metrics-core-3.1.2.jar:/Users/mohamedboussaa/.m2/repository/org/opensaml/opensaml-saml-api/3.3.0/opensaml-saml-api-3.3.0.jar:/Users/mohamedboussaa/.m2/repository/org/opensaml/opensaml-xmlsec-api/3.3.0/opensaml-xmlsec-api-3.3.0.jar:/Users/mohamedboussaa/.m2/repository/org/opensaml/opensaml-soap-api/3.3.0/opensaml-soap-api-3.3.0.jar:/Users/mohamedboussaa/.m2/repository/org/opensaml/opensaml-security-impl/3.3.0/opensaml-security-impl-3.3.0.jar:/Users/mohamedboussaa/.m2/repository/org/opensaml/opensaml-security-api/3.3.0/opensaml-security-api-3.3.0.jar:/Users/mohamedboussaa/.m2/repository/org/cryptacular/cryptacular/1.1.1/cryptacular-1.1.1.jar:/Users/mohamedboussaa/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.54/bcprov-jdk15on-1.54.jar:/Users/mohamedboussaa/.m2/repository/org/opensaml/opensaml-xmlsec-impl/3.3.0/opensaml-xmlsec-impl-3.3.0.jar:/Users/mohamedboussaa/.m2/repository/net/shibboleth/utilities/java-support/7.3.0/java-support-7.3.0.jar:/Users/mohamedboussaa/.m2/repository/joda-time/joda-time/2.9/joda-time-2.9.jar:/Users/mohamedboussaa/.m2/repository/org/opensaml/opensaml-xacml-impl/3.3.0/opensaml-xacml-impl-3.3.0.jar:/Users/mohamedboussaa/.m2/repository/org/opensaml/opensaml-xacml-api/3.3.0/opensaml-xacml-api-3.3.0.jar:/Users/mohamedboussaa/.m2/repository/org/opensaml/opensaml-xacml-saml-impl/3.3.0/opensaml-xacml-saml-impl-3.3.0.jar:/Users/mohamedboussaa/.m2/repository/org/opensaml/opensaml-xacml-saml-api/3.3.0/opensaml-xacml-saml-api-3.3.0.jar:/Users/mohamedboussaa/.m2/repository/org/jasypt/jasypt/1.9.2/jasypt-1.9.2.jar:/Users/mohamedboussaa/.m2/repository/org/apache/wss4j/wss4j-policy/2.2.2/wss4j-policy-2.2.2.jar:/Users/mohamedboussaa/.m2/repository/org/apache/wss4j/wss4j-ws-security-stax/2.2.2/wss4j-ws-security-stax-2.2.2.jar:/Users/mohamedboussaa/.m2/repository/org/apache/wss4j/wss4j-bindings/2.2.2/wss4j-bindings-2.2.2.jar:/Users/mohamedboussaa/.m2/repository/org/apache/wss4j/wss4j-ws-security-policy-stax/2.2.2/wss4j-ws-security-policy-stax-2.2.2.jar:/Users/mohamedboussaa/.m2/repository/org/apache/cxf/cxf-rt-rs-security-jose/3.2.5/cxf-rt-rs-security-jose-3.2.5.jar:/Users/mohamedboussaa/.m2/repository/org/apache/cxf/cxf-rt-security/3.2.5/cxf-rt-security-3.2.5.jar:/Users/mohamedboussaa/.m2/repository/org/apache/cxf/cxf-rt-rs-json-basic/3.2.5/cxf-rt-rs-json-basic-3.2.5.jar:/Users/mohamedboussaa/.m2/repository/org/springframework/spring-context/4.3.20.RELEASE/spring-context-4.3.20.RELEASE.jar:/Users/mohamedboussaa/.m2/repository/org/springframework/spring-aop/4.3.20.RELEASE/spring-aop-4.3.20.RELEASE.jar:/Users/mohamedboussaa/.m2/repository/org/springframework/spring-beans/4.3.20.RELEASE/spring-beans-4.3.20.RELEASE.jar:/Users/mohamedboussaa/.m2/repository/org/springframework/spring-expression/4.3.20.RELEASE/spring-expression-4.3.20.RELEASE.jar:/Users/mohamedboussaa/.m2/repository/org/apache/cxf/cxf-testutils/3.2.5/cxf-testutils-3.2.5.jar:/Users/mohamedboussaa/.m2/repository/org/apache/cxf/cxf-rt-wsdl/3.2.5/cxf-rt-wsdl-3.2.5.jar:/Users/mohamedboussaa/.m2/repository/wsdl4j/wsdl4j/1.6.3/wsdl4j-1.6.3.jar:/Users/mohamedboussaa/.m2/repository/org/apache/geronimo/javamail/geronimo-javamail_1.4_mail/1.8.4/geronimo-javamail_1.4_mail-1.8.4.jar:/Users/mohamedboussaa/.m2/repository/de/bwaldvogel/mongo-java-server/1.7.0/mongo-java-server-1.7.0.jar:/Users/mohamedboussaa/.m2/repository/de/bwaldvogel/mongo-java-server-core/1.7.0/mongo-java-server-core-1.7.0.jar:/Users/mohamedboussaa/.m2/repository/io/netty/netty-transport/4.1.9.Final/netty-transport-4.1.9.Final.jar:/Users/mohamedboussaa/.m2/repository/io/netty/netty-buffer/4.1.9.Final/netty-buffer-4.1.9.Final.jar:/Users/mohamedboussaa/.m2/repository/io/netty/netty-common/4.1.9.Final/netty-common-4.1.9.Final.jar:/Users/mohamedboussaa/.m2/repository/io/netty/netty-resolver/4.1.9.Final/netty-resolver-4.1.9.Final.jar:/Users/mohamedboussaa/.m2/repository/io/netty/netty-codec/4.1.9.Final/netty-codec-4.1.9.Final.jar:/Users/mohamedboussaa/.m2/repository/de/bwaldvogel/mongo-java-server-memory-backend/1.7.0/mongo-java-server-memory-backend-1.7.0.jar:
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.749 s
[INFO] Finished at: 2019-11-26T12:22:16+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal eu.stamp-project:botsing-maven:1.0.7:botsing (default-cli) on project botsing-maven: Execution default-cli of goal eu.stamp-project:botsing-maven:1.0.7:botsing failed.: NullPointerException -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by cformisano** [comment]
> Wrong arguments. Input file name 'stacktrace.log' does not exist!

It seems that the file is not present in the same folder of the pom

**Comment by mboussaa** [comment]
It is though
<img width="209" alt="Screenshot 2019-11-27 at 17 15 06" src="https://user-images.githubusercontent.com/5878565/69740362-8b886000-1139-11ea-89ec-aeda3c7f46c6.png">

**Comment by cformisano** [comment]
You don not have to show it to me, maven complains of this :). 
However, your stack trace reports this error ("file stacktrace.log does not exist"): I cannot know why your maven instance cannot find the file, but it can't. Try to solve the problem and let's check if this is the root cause of your NullpointerException.
